import { createHash } from "node:crypto";
import type { ToolchainDeclaration } from "../manifest/types.js";

/**
 * Renders the toolchain Dockerfile from the manifest.
 *
 * Deterministic by contract: the same declaration always produces byte-identical
 * output, because the image tag is the hash of these bytes and that tag is the
 * only cache key. Anything time-dependent, environment-dependent or randomly
 * ordered in here silently defeats the cache and, with it, the guarantee that a
 * rebuild uses the same compiler.
 *
 * The split this file encodes: the operator states WHAT goes in the box (base
 * image, packages, versions), w7s states HOW Gecko is built (layer order, the
 * bootstrap invocation, where caches live). Nothing is added that the manifest
 * did not name.
 */
export function renderDockerfile(toolchain: ToolchainDeclaration): string {
  const apt = [...toolchain.aptPackages].sort();
  const extra = toolchain.extraCommands ?? [];

  const lines: string[] = [
    "# Generated by w7s from the manifest's toolchain block. Do not edit.",
    "# Editing this file changes nothing: it is re-rendered on every run, and the",
    "# image tag is the hash of its contents.",
    `FROM ${toolchain.baseImage}`,
    "",
    "ENV DEBIAN_FRONTEND=noninteractive",
    "ENV LANG=C.UTF-8",
    "",
  ];

  if (apt.length > 0) {
    lines.push(
      "RUN apt-get update \\",
      ...apt.map((pkg) => ` && apt-get install -y --no-install-recommends ${pkg} \\`),
      " && rm -rf /var/lib/apt/lists/*",
      "",
    );
  }

  lines.push(
    `ENV RUSTUP_HOME=/opt/rustup CARGO_HOME=/opt/cargo PATH=/opt/cargo/bin:$PATH`,
    `RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \\`,
    ` | sh -s -- -y --no-modify-path --default-toolchain ${toolchain.rustVersion} \\`,
    ` && rustc --version | grep -q '${toolchain.rustVersion}'`,
    "",
    `RUN cargo install sccache --version ${toolchain.sccacheVersion} --locked`,
    "ENV RUSTC_WRAPPER=sccache SCCACHE_DIR=/cache/sccache",
    "",
  );

  if (extra.length > 0) {
    lines.push("# extraCommands, verbatim and in order", ...extra.map((cmd) => `RUN ${cmd}`), "");
  }

  lines.push("WORKDIR /gecko-source", "");

  return `${lines.join("\n")}\n`;
}

/** The content-addressed local tag. The tag IS the cache key; nothing else is. */
export function toolchainImageTag(dockerfile: string): string {
  const hash = createHash("sha256").update(dockerfile, "utf8").digest("hex").slice(0, 16);
  return `w7s-toolchain:local-${hash}`;
}

export function dockerfileSha256(dockerfile: string): string {
  return createHash("sha256").update(dockerfile, "utf8").digest("hex");
}
