import type { ToolchainDeclaration } from "../manifest/types.js";

/**
 * The mozconfig handed to mach.
 *
 * MOZ_OBJDIR is written by w7s, never by the operator: where the object
 * directory lives is wiring, and pointing it anywhere else would silently break
 * the artifact layout. Everything else comes from `mozconfigOptions` in the
 * manifest, verbatim and in order, because what the browser is built WITH is the
 * operator's decision.
 */
export const OBJDIR_CONTAINER_PATH = "/gecko-binary";

export function renderMozconfig(toolchain: ToolchainDeclaration): string {
  const lines = [
    "# Generated by w7s. Do not edit: it is re-rendered on every build.",
    `mk_add_options MOZ_OBJDIR=${OBJDIR_CONTAINER_PATH}`,
    ...(toolchain.mozconfigOptions ?? []),
  ];
  return `${lines.join("\n")}\n`;
}
